version: '3.8'
services:
  web:
    image: ranazaeem11/my-web-app:latest
    ports:
      - "80:3000"
    depends_on:
      - mysql_db
    environment:
      - DB_HOST=mysql_db
    networks:
      - app-network
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app-network
volumes:
  db-data:
networks:
  app-network:
    driver: bridge